#!/usr/bin/env python3
"""One source of truth for the EdgeTRM breadth numbers: reads results/breadth/ and writes
reports/EDGETRM_MASTER_TABLES.md (one protocol per table, every number traceable to a file).

    python make_tables.py [--out ../reports/EDGETRM_MASTER_TABLES.md]
"""
import argparse
import glob
import json
import os
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
R = HERE / "results" / "breadth"
Q_MAIN = ["fp32", "w8c", "w6c", "w4g32", "w4c", "w4a", "w4t", "w3g32", "w3a", "w2g32"]
Q_A8 = ["w8c", "w8c+a8", "w4g32", "w4g32+a8", "w4c", "w4c+a8"]


def load(path):
    try:
        d = json.load(open(path))
    except Exception:
        return []
    return d.get("records", []) if isinstance(d, dict) else []


def recs(pattern):
    out = []
    for f in sorted(glob.glob(str(R / pattern))):
        if "smoke" in f:
            continue
        out += load(f)
    return out


def fmt(x, d=1):
    return "–" if x is None else f"{x*100:.{d}f}" if x <= 1.0 else f"{x:.{d}f}"


def cell(r, acc, fid):
    if r is None:
        return "–"
    s = fmt(r[acc])
    if fid and r.get(fid) is not None and r["quant"]["spec"] != "fp32":
        s += f" ({r[fid]:.2f})"
    return s


lines = []
P = lines.append

# ------------------------------------------------------------------ A. official ARC
P("# EdgeTRM master tables (auto-generated by `EdgeTRM/make_tables.py`; do not edit by hand)\n")
P("Every number comes from `EdgeTRM/results/breadth/`. Accuracy in %, carry fidelity in parentheses.\n")
P("## A. ARC-AGI-1, official protocol (all 400 tasks, 1000-augmentation vote), pass@2 / pass@1\n")
full = defaultdict(list)
for f in sorted(glob.glob(str(R / "arc_full" / "*_s*of*.json"))):
    tag = os.path.basename(f).rsplit("_s", 1)[0]
    for r in load(f):
        if "arc_pass1" in r:
            full[(tag, r["H_cycles"], r["nsup"], r["quant"]["spec"])].append(r)
rows = {}
for (tag, H, n, spec), rs in full.items():
    if len(rs) < 8:
        continue
    N = sum(r["n_puzzles"] for r in rs)
    rows[(H, n, spec)] = (sum(r["arc_pass2"] * r["n_puzzles"] for r in rs) / N,
                          sum(r["arc_pass1"] * r["n_puzzles"] for r in rs) / N, rs[0].get("fidelity_H"))
specs = ["fp32", "w8c", "w6c", "w4g32", "w4g128", "w4c", "w4a", "w3g32", "w3a", "w4t", "w2g32", "w8c+a8", "w4g32+a8"]
P("| config | " + " | ".join(specs) + " |")
P("|---|" + "---|" * len(specs))
for (H, n) in [(3, 16), (3, 8), (1, 16), (1, 8), (1, 4)]:
    cells = []
    for s in specs:
        v = rows.get((H, n, s))
        cells.append("–" if v is None else f"{v[0]*100:.2f} / {v[1]*100:.2f}" + (f" ({v[2]:.2f})" if s != "fp32" and v[2] else ""))
    if any(c != "–" for c in cells):
        label = f"H={H}, n={n}" + (" (published 44.6)" if (H, n) == (3, 16) else " (MCU config)" if (H, n) == (1, 8) else "")
        P(f"| {label} | " + " | ".join(cells) + " |")
P("")

# ------------------------------------------------------------------ B. families x quantizers
P("## B. Puzzle families at the deepest setting (puzzle-exact %, fidelity of the final carry), canonical single pass\n")
P("| family / task (fp32) | " + " | ".join(Q_MAIN[1:]) + " |")
P("|---|" + "---|" * (len(Q_MAIN) - 1))
fam = [("TRM attn, ARC-AGI-1 pass@1, H=3 n=16", recs("arc_attn_H3.json") + recs("arc_attn_a8.json"), "arc_pass1", "fidelity_H", lambda r: r["H_cycles"] == 3 and r["nsup"] == 16),
       ("TRM attn, Sudoku-Extreme, H=3 n=16", recs("sudoku_attn_*.json"), "pexact", "fidelity_H", lambda r: r["H_cycles"] == 3 and r["nsup"] == 16),
       ("TRM MLP, Sudoku-Extreme, H=3 n=16", recs("sudoku_mlp_*.json"), "pexact", "fidelity_H", lambda r: r["H_cycles"] == 3 and r["nsup"] == 16),
       ("HRM, Sudoku-Extreme, n=16", recs("hrm_sudoku_*.json"), "pexact", "fidelity_H", lambda r: r["nsup"] == 16 and r["H_cycles"] == max(x["H_cycles"] for x in recs("hrm_sudoku_all.json") if x["H_cycles"] <= 3)),
       ("TRM attn, Maze-Hard, H=3 n=16", recs("maze_attn_*.json"), "pexact", "fidelity_H", lambda r: r["H_cycles"] == 3 and r["nsup"] == 16),
       ("HRM, Maze-Hard, n=16", recs("hrm_maze_*.json"), "pexact", "fidelity_H", lambda r: r["nsup"] == 16 and r["H_cycles"] == max(x["H_cycles"] for x in recs("hrm_maze_n124.json") if x["H_cycles"] <= 3)),
       ("Deep-thinking maze 33×33, 100 iters", recs("dt_mazes*.json"), "acc", "fidelity", lambda r: str(r["size"]) == "33" and r["iters"] == 100),
       ("Deep-thinking chess (600k–700k), 60 iters", recs("dt_chess.json") + recs("dt_chess_a8.json"), "acc", "fidelity", lambda r: str(r["size"]) == "700000" and r["iters"] == 60),
       ("Deep-thinking prefix sums 512-bit, 100 iters", recs("dt_prefix_sums*.json"), "acc", "fidelity", lambda r: str(r["size"]) == "512" and r["iters"] == 100)]
for name, rs, acc, fid, sel in fam:
    by = {}
    for r in rs:
        if sel(r):
            by.setdefault(r["quant"]["spec"], r)
    ref = by.get("fp32")
    P(f"| {name} ({fmt(ref[acc]) if ref else '–'}) | " + " | ".join(cell(by.get(q), acc, fid) for q in Q_MAIN[1:]) + " |")
P("")

# ------------------------------------------------------------------ C. depth gap
P("## C. Gap to fp32 (points) at the shallowest vs deepest setting — does depth compound the error?\n")
P("| family / task | quantizer | gap at n=1 | gap at n=16 |")
P("|---|---|---|---|")
for name, rs, acc, tasks in [("TRM attn ARC (pass@1)", recs("arc_attn_H3.json"), "arc_pass1", None),
                            ("TRM attn Sudoku", recs("sudoku_attn_all.json"), "pexact", None),
                            ("TRM MLP Sudoku", recs("sudoku_mlp_all.json"), "pexact", None),
                            ("HRM Sudoku", recs("hrm_sudoku_all.json"), "pexact", None),
                            ("TRM attn Maze", recs("maze_attn_n124.json") + recs("maze_attn_n816.json"), "pexact", None),
                            ("HRM Maze", recs("hrm_maze_n124.json") + recs("hrm_maze_n816.json"), "pexact", None)]:
    Hs = sorted({r["H_cycles"] for r in rs})
    H = 3 if 3 in Hs else Hs[-1]
    by = {(r["nsup"], r["quant"]["spec"]): r for r in rs if r["H_cycles"] == H}
    for q in ["w8c", "w4g32", "w4c", "w4t", "w3g32"]:
        g = []
        for n in (1, 16):
            a, b = by.get((n, "fp32")), by.get((n, q))
            g.append("–" if a is None or b is None else f"{(a[acc]-b[acc])*100:+.1f}")
        P(f"| {name} | {q} | {g[0]} | {g[1]} |")
P("")

# ------------------------------------------------------------------ D. activations
P("## D. Static INT8 activations (+a8) at one step vs the deepest setting (puzzle-exact %, fidelity)\n")
P("| task | setting | " + " | ".join(Q_A8) + " |")
P("|---|---|" + "---|" * len(Q_A8))
for name, rs, acc, fid, key in [("ARC pass@1", recs("arc_attn_H3.json") + recs("arc_attn_a8.json"), "arc_pass1", "fidelity_H", lambda r: (r["H_cycles"], r["nsup"])),
                                ("Sudoku-MLP", recs("sudoku_mlp_*.json"), "pexact", "fidelity_H", lambda r: (r["H_cycles"], r["nsup"])),
                                ("Sudoku-attn", recs("sudoku_attn_*.json"), "pexact", "fidelity_H", lambda r: (r["H_cycles"], r["nsup"])),
                                ("HRM Sudoku", recs("hrm_sudoku_*.json"), "pexact", "fidelity_H", lambda r: (r["H_cycles"], r["nsup"])),
                                ("Maze-attn", recs("maze_attn_*.json"), "pexact", "fidelity_H", lambda r: (r["H_cycles"], r["nsup"])),
                                ("HRM Maze", recs("hrm_maze_*.json"), "pexact", "fidelity_H", lambda r: (r["H_cycles"], r["nsup"]))]:
    Hs = sorted({r["H_cycles"] for r in rs})
    H = 3 if 3 in Hs else Hs[-1]
    by = {(r["nsup"], r["quant"]["spec"]): r for r in rs if r["H_cycles"] == H}
    for n in (1, 16):
        ref = by.get((n, "fp32"))
        P(f"| {name} (fp32 {fmt(ref[acc]) if ref else '–'}) | H={H} n={n} | " + " | ".join(cell(by.get((n, q)), acc, fid) for q in Q_A8) + " |")
P("")

# ------------------------------------------------------------------ E. looped LMs
P("## E. Looped language models on GSM8K (greedy accuracy %, n in brackets; teacher-forced NLL / fidelity from the no-gen runs)\n")
P("| model, depth | bf16 | w8c | w6c | w4g32 | w4c | w4a | w4t | w3a |")
P("|---|---|---|---|---|---|---|---|---|")
for model, gen_files, nogen in [("Huginn-0125", ["huginn_gsm8k_s4.json", "huginn_gsm8k_s8.json", "huginn_gsm8k_s16.json", "huginn_gsm8k_s32.json", "huginn_gsm8k_s64_n50.json"], "huginn_gsm8k_s4_8_16_32_64_nogen.json"),
                                ("Ouro-1.4B", ["ouro14_gsm8k_s1_2.json", "ouro14_gsm8k_s3_4_n100.json", "ouro14_gsm8k_s6_n100.json", "ouro14_gsm8k_s8_n100.json"], "ouro14_gsm8k_s1_2_3_4_6_8_nogen.json"),
                                ("Ouro-2.6B", ["ouro26_gsm8k_s1_2.json", "ouro26_gsm8k_s3_4_n100.json", "ouro26_gsm8k_s6_n100.json", "ouro26_gsm8k_s8_n100.json"], "ouro26_gsm8k_s1_2_3_4_6_8_nogen.json")]:
    gen = {}
    for f in gen_files:
        for r in load(R / "lambda" / f):
            if r.get("acc") is not None:
                gen.setdefault((r["steps"], r["quant"]["spec"]), r)
    ng = {(r["steps"], r["quant"]["spec"]): r for r in load(R / "lambda" / nogen)}
    for s in sorted({k[0] for k in list(gen) + list(ng)}):
        cells = []
        for q in ["bf16", "w8c", "w6c", "w4g32", "w4c", "w4a", "w4t", "w3a"]:
            g, t = gen.get((s, q)), ng.get((s, q))
            c = f"{g['acc']*100:.1f} [{g['n']}]" if g else "–"
            if t:
                c += f" nll {t['nll']:.2f}" + (f" φ {t['fidelity']:.2f}" if q != "bf16" else "")
            cells.append(c)
        P(f"| {model}, {s} {'steps' if model.startswith('Huginn') else 'loops'} | " + " | ".join(cells) + " |")
P("")

# ------------------------------------------------------------------ F. training trajectory
P("## F. Trained Sudoku variants along training (H=3, n=16, puzzle-exact %; per-tensor INT4 fidelity in brackets)\n")
P("| run | step | fp32 | w8c | w4c | w4t |")
P("|---|---|---|---|---|---|")
for f in sorted(glob.glob(str(R / "lambda" / "variant_*.json")), key=lambda p: (p.rsplit("_", 1)[0], int(p.rsplit("_", 1)[1][:-5]))):
    rs = [r for r in load(f) if r["H_cycles"] == 3 and r["nsup"] == 16]
    by = {r["quant"]["spec"]: r for r in rs}
    if "fp32" in by:
        name, step = os.path.basename(f)[8:-5].rsplit("_", 1)
        w4t = by.get("w4t")
        w4t_s = "–" if w4t is None else "%s (%.2f)" % (fmt(w4t["pexact"]), w4t["fidelity_H"])
        w8c_s = fmt(by["w8c"]["pexact"]) if "w8c" in by else "–"
        w4c_s = fmt(by["w4c"]["pexact"]) if "w4c" in by else "–"
        P(f"| {name} | {step} | {fmt(by['fp32']['pexact'])} | {w8c_s} | {w4c_s} | {w4t_s} |")
P("")

# ------------------------------------------------------------------ G. devices
P("## G. Devices\n")
st = json.load(open(R / "aihub_status.json")) if (R / "aihub_status.json").exists() else []
if st:
    from collections import Counter
    c = Counter((r["kind"], r["status"]) for r in st)
    devs = sorted({r["device"] for r in st if r["kind"] == "compile" and r["status"] == "SUCCESS"})
    P(f"AI Hub: {c[('compile','SUCCESS')]} compiles succeeded on {len(devs)} devices, {c[('compile','FAILED')]} failed, "
      f"{sum(v for (k, s), v in c.items() if s not in ('SUCCESS', 'FAILED'))} still queued; "
      f"{c[('profile','SUCCESS')]} profiles executed.\n")
    prof = [r for r in st if r["kind"] == "profile" and r["status"] == "SUCCESS"]
    if prof:
        P("| task | precision | device | ms | peak MB |")
        P("|---|---|---|---|---|")
        for r in sorted(prof, key=lambda r: (r["task"], r["precision"], r["device"])):
            P(f"| {r['task']} | {r['precision']} | {r['device']} | {r['ms']:.2f} | {r['peak_mb']:.1f} |")
vela = load(R / "vela_breadth.json")
if vela:
    P(f"\nVela: {len(vela)} (accelerator, system, memory-mode, task, precision) configurations in `vela_breadth.json`.\n")

ap = argparse.ArgumentParser()
ap.add_argument("--out", default=str(HERE.parent / "reports" / "EDGETRM_MASTER_TABLES.md"))
a = ap.parse_args()
Path(a.out).write_text("\n".join(lines) + "\n")
print("wrote", a.out, len(lines), "lines")
